/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package be.seeseemelk.raviolios.plugin.cpp;

import org.gradle.api.Project;
import org.gradle.api.Plugin;
import org.gradle.api.artifacts.Configuration;
import org.gradle.api.tasks.TaskProvider;

/**
 * Allows building C/C++ kernel sources.
 */
public class CppBuildPlugin implements Plugin<Project>
{
	public void apply(Project project)
	{
		project.getConfigurations().create("source");
		CppExtension extensions = project.getExtensions().create("cpp", CppExtension.class);
		TaskProvider<CppTask> task = project.getTasks().register("cpp", CppTask.class, t -> {
			t.doFirst(ta -> {
				//System.out.println("Extensions: " + extensions.getDependencies().get());
				Configuration configuration = project.getConfigurations().getByName("source");
				configuration.getDependencies().all(dep ->
				{
					System.out.println(dep.getName());
				});
				//System.out.println("Projects: " + project.getDependencies().get);
			});
		});
		task.get().setGroup("Build");
		task.get().setDescription("Build C/C++ files");
	}
}
