/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package be.seeseemelk.raviolios.plugin.cpp;

import org.gradle.testfixtures.ProjectBuilder;
import org.gradle.api.Project;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class CppBuildPluginTest
{
    @Test
    void pluginRegistersATask()
    {
        Project project = ProjectBuilder.builder().build();
        project.getPlugins().apply("be.seeseemelk.raviolios.cpp");

        assertNotNull(project.getTasks().findByName("compileCpp"));
    }
}
